on: [push]

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: deploy
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: deploy file
          uses: wlixcc/SFTP-Deploy-Action@v1.2.4
          with:
              username: 'root'
              server: '146.59.196.181'
              ssh_private_key: ${{ SSH_PRIVATE_KEY }} 
              local_path: './static/*'
              remote_path: '/var/www/theBigProject'
              sftpArgs: '-o ConnectTimeout=5'
